In [1]:
!git clone https://github.com/KHiMAeRA05/PMLDL_movie_recommender_system

Cloning into 'PMLDL_movie_recommender_system'...
remote: Enumerating objects: 69, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 69 (delta 20), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (69/69), 3.27 MiB | 3.41 MiB/s, done.

In [2]:
# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
!cd /kaggle/working/PMLDL_movie_recommender_system

In [14]:
# Load the MovieLens 100K dataset
# Assuming the dataset is loaded into a DataFrame named 'df'
# You may need to adjust the file paths based on your directory structure
df = pd.read_csv('/kaggle/working/PMLDL_movie_recommender_system/data/interim/preprocessed_data.csv')
df

,user_id,item_id,rating,age,gender_F,gender_M,occupation_administrator,occupation_artist,occupation_doctor,occupation_educator,...,occupation_marketing,occupation_none,occupation_other,occupation_programmer,occupation_retired,occupation_salesman,occupation_scientist,occupation_student,occupation_technician,occupation_writer
0,196,242,3,49,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,196,393,4,49,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,196,381,4,49,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,196,251,3,49,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
4,196,655,5,49,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,941,919,5,20,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
99996,941,273,3,20,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
99997,941,1,5,20,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
99998,941,294,4,20,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
99999,941,1007,4,20,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

# Start training

In [5]:
# Install Surprise library
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /opt/conda/lib/python3.10/site-packages (1.1.3)
Requirement already satisfied: joblib>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from scikit-surprise) (1.3.2)
Requirement already satisfied: numpy>=1.17.3 in /opt/conda/lib/python3.10/site-packages (from scikit-surprise) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in /opt/conda/lib/python3.10/site-packages (from scikit-surprise) (1.11.3)

In [25]:
# Import necessary libraries
from surprise import Dataset, Reader, SVD, dump
from surprise.model_selection import cross_validate, train_test_split
from surprise import accuracy

In [17]:
reader = Reader(rating_scale=(1, 5))
dataset = Dataset.load_from_df(df[['user_id', 'item_id', 'rating']], reader)

trainset, testset = train_test_split(dataset, test_size=0.2)

In [18]:
# Choose the SVD algorithm (you can experiment with other algorithms)
model = SVD()

# Train the model on the training set
model.fit(trainset)

In [19]:
# Make predictions on the test set
predictions = model.test(testset)

# Evaluate the model
accuracy.rmse(predictions)

RMSE: 0.9319

0.9318610051761178

In [26]:
# Save the trained model
model_filename = 'model.pkl'
dump.dump(model_filename, algo=model)